name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Keep this if your default branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build frontend and backend
      run: |
        npm run build:frontend
        npm run build

    - name: Zip app for deployment
      run: zip -r app.zip . -x "*.git*" "node_modules/*" "client/node_modules/*"

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: talenthub-app             # ✅ Your EB Application Name
        environment_name: Talenthub-app-env          # ✅ Your EB Environment Name
        region: ap-south-1                         # ✅ Your AWS Region (e.g., us-east-1, ap-south-1)
        version_label: ${{ github.sha }}
        deployment_package: app.zip
